name: model_generator
description: Dart tool to automaticly generate models from a yml file to speed up your development flow.
version: 1.0.0
homepage: https://github.com/icapps/flutter-model-generator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.6.4
  yaml: ^2.2.0
  recase: ^3.0.0

dev_dependencies:
  test: ^1.11.1
