name: model_generator
description: Dart tool to automaticly generate models from a yml file to speed up your development flow.
version: 2.1.1
homepage: https://github.com/icapps/flutter-model-generator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.7.0
  yaml: ^2.2.1

dev_dependencies:
  test: ^1.15.3
