OGM:
  type: object
  properties:
    structuredMessage:
      required: true
      type: string
    beneficiary:
      required: true
      type: string
    beneficiaryIBAN:
      required: true
      type: string
    test_Test:
      required: true
      type: string
    some_Thing:
      required: true
      type: string
    some_ThinG_huGE:
      required: true
      type: string
Testing:
  path: user
  type: object
  properties:
    isFavourite:
      ignore: true
      type: string
    structuredMessage:
      type: string
    beneficiary:
      required: true
      type: string
    beneficiaryIBAN:
      type: string
UserProfileData:
  path: user/profile
  type: object
  properties:
    firstName:
      required: true
      type: string
    lastName:
      required: true
      type: string
    standardLanguage:
      required: true
      type: string
    mainAccountNumber:
      required: true
      type: string
    legalEmail:
      required: true
      type: string
    phones:
      required: true
      type: Testing
    legalAddress:
      required: true
      type: OGM
    offTrack:
      type: array
      items:
        type: string
    onTrack:
      type: array
      items:
        type: OGM
    persons:
      type: array
      items:
        type: Person
Person:
  path: user/person/
  type: object
  properties:
    firstName:
      required: true
      type: string